apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: 13.63.130.160:5000/vote
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: redis
        - name: DB_HOST
          value: db
